spring.application.name=TankClean

spring.profiles.active=prod

server.port=${PORT:8080}


spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

app.default-admin.name=Admin
app.default-admin.email=admin@123.com
app.default-admin.phone=9096651403
app.default-admin.password=Admin@123


