spring.datasource.url=${jdbc:postgresql://tankclean_user:ufQsVpbI2SOneAbNpQQCB1envTQmJ9QE@dpg-d9l0j7jm8hqs7390s1a0-a/tankclean}
spring.datasource.username=${tankclean_user}
spring.datasource.password=${ufQsVpbI2SOneAbNpQQCB1envTQmJ9QE}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
